logo: "assets/images/divyabidarahalli@gmail.com_11.jpg"
title: "Divyashree Bidarahalli" 
description: "Data Analyst | SQL | Power BI | Python | Tableau"
theme: jekyll-theme-minimal
sass:
  load_paths:
    - _sass
header_pages:
  - _pages/projects.md
  - _pages/cv.md

