title: "Divyashree Bidarahalli | Data Analyst and Business Intelligence Analyst"
description: "Data Analyst | SQL | Power BI | Python | Tableau"
theme: jekyll-theme-minimal
social_links:
  - { platform: github, user_url: "https://github.com/divyashree-db" }
  - { platform: linkedin, user_url: "https://www.linkedin.com/in/divyashree-bidarahalli/" }
  - { platform: tableau, user_url: "https://public.tableau.com/profile/yourname" }
