title: "Divyashree Bidarahalli" 
logo: assets/images/divyabidarahalli@gmail.com_1.jpg
description: "Data Analyst | SQL | Power BI | Python | Tableau"
theme: jekyll-theme-minimal
skin: custom
header_pages:
  - _pages/projects.md
  - _pages/cv.md
